"""create habit records

Revision ID: 46a69af9cd8b
Revises: 4a10bc839a7f
Create Date: 2026-08-12 20:05:26.462043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46a69af9cd8b'
down_revision: Union[str, Sequence[str], None] = '4a10bc839a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_records', sa.Column('record_date', sa.Date(), nullable=False))
    op.alter_column('habit_records', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('habit_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('habit_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_habit_records_record_date'), 'habit_records', ['record_date'], unique=False)
    op.create_unique_constraint('uq_habit_record_date', 'habit_records', ['habit_id', 'record_date'])
    op.drop_constraint(op.f('habit_records_habit_id_fkey'), 'habit_records', type_='foreignkey')
    op.create_foreign_key(None, 'habit_records', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('habit_records', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_records', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'habit_records', type_='foreignkey')
    op.create_foreign_key(op.f('habit_records_habit_id_fkey'), 'habit_records', 'habits', ['habit_id'], ['id'])
    op.drop_constraint('uq_habit_record_date', 'habit_records', type_='unique')
    op.drop_index(op.f('ix_habit_records_record_date'), table_name='habit_records')
    op.alter_column('habit_records', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('habit_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('habit_records', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('habit_records', 'record_date')
    # ### end Alembic commands ###
