"""rename habit type to data_type

Revision ID: 4a10bc839a7f
Revises: 7ea310edba54
Create Date: 2026-08-12 18:47:40.053846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a10bc839a7f'
down_revision: Union[str, Sequence[str], None] = '7ea310edba54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('data_type', sa.String(length=20), nullable=False))
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('habits', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('habits', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('habits', 'data_type')
    # ### end Alembic commands ###
