"""add habit record timestamp defaults

Revision ID: aa07a00c1ec0
Revises: 46a69af9cd8b
Create Date: 2026-08-12 20:42:27.774171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa07a00c1ec0'
down_revision: Union[str, Sequence[str], None] = '46a69af9cd8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
