"""create flight price history table

Revision ID: 31746e1098b2
Revises: a4fb808645fc
Create Date: 2026-08-16 21:47:06.890859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31746e1098b2'
down_revision: Union[str, Sequence[str], None] = 'a4fb808645fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_route_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('outbound_date', sa.String(length=20), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flight_route_id'], ['flight_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_price_history_flight_route_id'), 'flight_price_history', ['flight_route_id'], unique=False)
    op.create_index(op.f('ix_flight_price_history_id'), 'flight_price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_price_history_id'), table_name='flight_price_history')
    op.drop_index(op.f('ix_flight_price_history_flight_route_id'), table_name='flight_price_history')
    op.drop_table('flight_price_history')
    # ### end Alembic commands ###
